# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: insidion
  host: localhost
  username: insidion
  password: "8299512vs008921"
  encoding: utf8